load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "message_manager",
    srcs = ["message_manager.cc", "message.cc", "parameter.cc"],
    hdrs = ["message_manager.h", "message.h", "parameter.h"],
    includes = ["."],
    deps = [],
    visibility = ["//visibility:public"],
)
